import React from 'react'

function N240822Firma() {
  return (
    <div className="container text-start fs-5">
      <hr />
      <h2>Acto de firma de adjudicacion</h2>
      <hr />
      <div className="d-flex flex-column">
        <p>Se trata de la convocatoria PICTO UCTH, que destinará la suma de $ 168.000.000 por el término de 24 meses para desarrollo de proyectos con el objetivo de fortalecer en los hospitales las capacidades de producción de conocimientos, formación, capacitación e implementación de resultados en los servicios de salud. <br/>
        La ministra de Salud de la Nación, Carla Vizzotti, y su par de Ciencia, Tecnología e Innovación, Daniel Filmus, participaron hoy en el Hospital Nacional en Red “Lic. Laura Bonaparte” del acto de firma de adjudicaciones para los nueve hospitales que aplicaron a la convocatoria a Proyectos de innovación científico tecnológica para Unidades de Conocimiento Traslacional Hospitalarias (PICTO UCTH).</p><br/>
        <p>La convocatoria PICTO UCTH, organizada junto a la Agencia I+D+i, destinó mediante el Fondo para la Investigación Científica y Tecnológica (FONCyT) la suma de $ 168.000.000 por el término de 24 meses para el desarrollo de proyectos con el objetivo de fortalecer en los hospitales las capacidades de producción de conocimientos, formación, capacitación e implementación de resultados en los servicios de salud, a fin de generar un alto impacto en la calidad de atención y dar respuestas a problemas críticos y/o prevalentes en los contextos asistenciales y sociosanitarios.</p>
        <p>La iniciativa se produce en el marco del Plan Nacional de Conocimiento Traslacional en Salud para la Red de Hospitales y del Convenio de Cooperación y Colaboración entre el Ministerio de Ciencia, Tecnología e Innovación de la Nación, el Ministerio de Salud de la Nación y Agencia I+D+i. Así se financiarán en esta primera etapa un conjunto de proyectos de alta relevancia sanitaria, que serán ejecutados por los equipos que integran Unidades de Conocimiento Traslacional (UCTH) creadas en hospitales y servicios de salud públicos. 
        “Quiero felicitarlos por el trabajo realizado y por esta articulación que nos potencia y sinergiza”, destacó Vizzotti, al tiempo que reconoció la labor de “todos los hospitales que están recibiendo estos fondos para poder investigar y seguir generando conocimiento que impacte en la salud de las personas”.    
        Y agregó: “Cuando aunamos esfuerzos para obtener mejores resultados y para tener un Estado presente, somos mucho más potentes y este encuentro es la demostración de eso. Este espacio sirve para destacar lo que significa el desarrollo y la generación de conocimiento para la salud, y remarca además la importancia de la articulación que hemos logrado el Ministerio de Ciencia, Tecnología e Innovación, y con la Agencia I+D+i”. <br/>
        El ministro Filmus coincidió con su par de Salud y destacó el “trabajo estrecho que tenemos entre los dos ministerios en múltiples temáticas, que no solo conducen a una articulación interministerial sino interdisciplinaria”. En relación al conocimiento traslacional y sus posibilidades, señaló que “el hecho de que los mejores trabajen con los que más lo necesitan juega un rol sustantivo. Hay una potencialidad enorme en este campo y tenemos que profundizar eso aún más”. “Ese es el rol del Estado, estar ahí para garantizar la salud como derecho básico y fundamental”, completó. <br/>
        “La pandemia demostró que quienes monopolizan el conocimiento tienen la decisión sobre la vida y la muerte de las poblaciones, y nosotros venimos a entrar en esa disputa para ser soberanos en la capacidad de tomar decisiones. Por eso el trabajo que venimos desarrollando con Salud, fortaleciendo la presencia del Estado, proveyendo de recursos a los investigadores y fomentando el trabajo interministerial e interdisciplinario que transforme las ideas en proyectos”, aseguró. <br/>
        Por su parte, el titular de la Agencia I+D+i, Fernando Peirano, remarcó la importancia de la convocatoria PICTO UCTH y señaló que “el impacto de la promoción no está solo en el financiamiento, sino en la capacidad de constituir comunidades, redes, espacios con distintas instituciones y profesionales que tienen una agenda compartida. En ese sentido, avanzamos este paso para poner en relieve la función de la investigación en los hospitales, dándoles un peso institucional propio a las unidades de conocimiento hospitalario traslacional”. <br/>
        A su turno, el secretario de Calidad en Salud, Alejandro Collia, puso en valor la alianza estratégica que se ha consolidado entre el Ministerio de Salud y el Ministerio de Ciencia, Tecnología e Innovación que ha permitido no solo la generación de conocimiento, sino que también ha posibilitado “que en cada uno de estos lugares se pudieran desarrollar investigaciones in situ y que estos hospitales puedan participar, sumar y lograr mejores condiciones de políticas sanitarias para toda la población”. <br/>
        Los hospitales y servicios de salud que aplicaron en esta etapa son: el Hospital Nacional “Profesor Alejandro Posadas”; el Hospital de Pediatría “Prof. Dr. Juan P. Garrahan”; el Hospital de Alta Complejidad “El Calafate Gobernador Cepernic-Presidente Kirchner”; el Hospital Nacional en Red especializado en Salud Mental y Adicciones “Lic. Laura Bonaparte”; el Hospital de Alta Complejidad en Red El Cruce “Dr. Néstor Carlos Kirchner”; y el Instituto Nacional de Rehabilitación Psicofísica del Sur INAREPS. <br/>
        Además, en el marco de la estrategia federal serán financiados proyectos que se desarrollarán en las UCTH del Hospital Universitario de Maternidad y Neonatología de Córdoba; el Hospital Arturo Oñativia, Provincia de Salta; y el Hospital Mi Pueblo de la Provincia de Buenos Aires. <br/>
        También participaron del encuentro la subsecretaria de Gestión de Servicios e Institutos, Edith Benedetti; la subsecretaria de Articulación Federal, Verónica De Cristófaro; la directora de Difusión del Conocimiento, Daniela Álvarez; y la directora del Hospital Bonaparte, Beatriz Baldelli. <br/></p>
      </div>
    </div>
  )
}

export default N240822Firma